const COMMISSION_RATES = {
  SIGNUP_BONUS: parseFloat(process.env.SIGNUP_BONUS) || 1,
  LEVEL1: parseFloat(process.env.LEVEL1_COMMISSION) || 10,
  LEVEL2: parseFloat(process.env.LEVEL2_COMMISSION) || 5,
  LEVEL3: parseFloat(process.env.LEVEL3_COMMISSION) || 2.5,
  LEVEL4: parseFloat(process.env.LEVEL4_COMMISSION) || 1,
  REWARD_THRESHOLD: parseFloat(process.env.REWARD_THRESHOLD) || 10000,
  REWARD_AMOUNT: parseFloat(process.env.REWARD_AMOUNT) || 500,
};

const TRANSACTION_TYPES = {
  SIGNUP_BONUS: 'SIGNUP_BONUS',
  DIRECT_REFERRAL: 'DIRECT_REFERRAL',
  LEVEL_COMMISSION: 'LEVEL_COMMISSION',
  REWARD_INCOME: 'REWARD_INCOME',
  WITHDRAWAL: 'WITHDRAWAL',
  INVESTMENT: 'INVESTMENT',
};

const TRANSACTION_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED',
};

const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
};

const WITHDRAWAL_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
};

const LEVELS = {
  LEVEL1: 1,
  LEVEL2: 2,
  LEVEL3: 3,
  LEVEL4: 4,
};

module.exports = {
  COMMISSION_RATES,
  TRANSACTION_TYPES,
  TRANSACTION_STATUS,
  USER_STATUS,
  WITHDRAWAL_STATUS,
  LEVELS,
};